# /ipsec-server/config/ipsec.conf
config setup
    charondebug="ike 2, cfg 2"
    strictcrlpolicy=no
    uniqueids=no

conn %default
    keyexchange=ikev2
    ikelifetime=60m
    keylife=20m
    rekeymargin=3m
    keyingtries=1
    authby=secret
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!

conn myvpn
    left=%any
    leftid=@vpn-server
    leftsubnet=0.0.0.0/0
    leftcert=server.crt
    right=%any
    rightdns=8.8.8.8
    rightsourceip=10.10.10.0/24
    auto=add